context:
  name: libmemcached
  series: "1.0"
  version: "1.0.18"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://launchpad.net/${{ name }}/${{ series }}/${{ version }}/+download/${{ name }}-${{ version }}.tar.gz
  sha256: e22c0bb032fde08f53de9ffbc5a128233041d9f33b5de022c0978a2149885f82
  patches:
    # thanks to http://stackoverflow.com/questions/27004144/how-can-i-install-libmemcached-for-mac-os-x-yosemite-10-10-in-order-to-install-t
    - if: osx
      then:
        - osx.configure.patch
        - osx.memflush.patch
    # Taken from this bug report
    # ref: https://bugs.launchpad.net/libmemcached/+bug/1663985
    - if: linux
      then:
        - libmemcached-build.patch

build:
  number: 1004
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - if: unix
      then:
        - pkg-config
        - libtool
        - gnuconfig
    - if: linux and (build_platform != target_platform)
      then:
        - ${{ cdt("libuuid") }}
  host:
    - glib
  run_exports:
    - ${{ pin_subpackage("libmemcached", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f ${PREFIX}/lib/libmemcached.a
          - test -f ${PREFIX}/lib/libmemcached${SHLIB_EXT}
      - if: win
        then:
          - if not exist %LIBRARY_LIB%\libmemcached.lib (exit 1)
          - if not exist %LIBRARY_LIB%\libmemcached${SHLIB_EXT} (exit 1)

about:
  homepage: http://libmemcached.org
  license: BSD-3-Clause
  license_file: COPYING
  summary: libMemcached is an open source C/C++ client library and tools for the memcached server (http://danga.com/memcached).
  description: |
    It has been designed to be light on memory usage, thread safe, and provide full access to server side methods.

extra:
  recipe-maintainers:
    - bollwyvl
    - munechika-koyo
